import Head from 'next/head';
import Image from 'next/image';

export default function HomePage() {
  return (
    <div className="min-h-screen px-8 sm:px-20 flex flex-col justify-center items-center h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-20 flex flex-col justify-center items-center flex-grow">
        <h1 className="text-6xl leading-normal text-center">
          Welcome to <a className="text-blue-600" href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-center text-lg">
          Get started by editing{' '}
          <code className="bg-gray-100 p-2 rounded">pages/index.js</code>
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-4xl mt-12">
          <a href="https://nextjs.org/docs" className="p-6 text-left border rounded text-lg hover:border-blue-600 hover:text-blue-600 transition-colors">
            <h2 className="text-2xl leading-9 mb-4">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="p-6 text-left border rounded text-lg hover:border-blue-600 hover:text-blue-600 transition-colors">
            <h2 className="text-2xl leading-9 mb-4">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="p-6 text-left border rounded text-lg hover:border-blue-600 hover:text-blue-600 transition-colors"
          >
            <h2 className="text-2xl leading-9 mb-4">Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="p-6 text-left border rounded text-lg hover:border-blue-600 hover:text-blue-600 transition-colors"
          >
            <h2 className="text-2xl leading-9 mb-4">Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="w-full h-20 border-t flex items-center justify-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center flex-grow"
        >
          Powered by{' '}
          <span className="h-4 flex-col">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
